app = 'oaamonitor'
primary_region = 'bos'

[build]

[env]
  DATABASE_PATH = '/data/oaamonitor.db'
  PORT = '8080'

[[mounts]]
  source = 'oaamonitor_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
