app = 'oaamonitor'
primary_region = 'bos'

[build]
  [build.args]
    GO_VERSION = '1.25.0'

[env]
  DATABASE_PATH = '/data/oaamonitor.db'
  DOWNLOAD_DATABASE = 'true'
  UPLOAD_DATABASE = 'true'
  PORT = '8080'

[[mounts]]
  source = 'oaamonitor_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
